const CardData = 
[
    {
        id: 1,
        name: "Gülay Yüksel",
        title: "Tuval üzerinde yağlı boya",
        size: "50 cm X 50cm",
        year: "Yapım Yılı: 2023",
        price: "25.000 TL",
        image: "./art/img1.jpeg",
    },
    {
        id: 2,
        name: "Sibel Ünalan",
        title: "Tuval üzerinde yağlı boya",
        size: "42 cm X 30cm",
        year: "Yapım Yılı: 2023",
        price: "6.000 TL",
        image: "./art/img2.jpg",
    },
    {
        id: 3,
        name: "Pınar Kalem",
        title: "Tuval üzerinde yağlı boya",
        size: "50 cm X 50cm",
        year: "Yapım Yılı: 2024",
        price: "12.000 TL",
        image: "./art/img3.jpg",
    },
    {
        id: 4,
        name: "Raşit Altun",
        title: "Tuval üzerinde yağlı boya",
        size: "72 cm X 72cm",
        year: "Yapım Yılı: 2021",
        price: "5.000 TL",
        image: "./art/img4.jpg",
    },
    {
        id: 5,
        name: "Ali Öner",
        title: "Tuval üzerinde yağlı boya",
        size: "80 cm X 80cm",
        year: "Yapım Yılı: 2024",
        price: "15.000 TL",
        image: "./art/img5.jpg",
    },
    {
        id: 6,
        name: "Ali Öner",
        title: "Tuval üzerinde yağlı boya",
        size: "80 cm X 80cm",
        year: "Yapım Yılı: 2023",
        price: "12.500 TL",
        image: "./art/img6.jpg",
    },
    {
        id: 7,
        name: "Pınar Kanber",
        title: "Tuval üzerinde yağlı boya",
        size: "90 cm X 90cm",
        year: "Yapım Yılı: 2016",
        price: "11.000 TL",
        image: "./art/img7.jpeg",
    },
    {
        id: 8,
        name: "Nilgün Şener",
        title: "Tuval üzerinde yağlı boya",
        size: "70 cm X 70cm",
        year: "Yapım Yılı: 2023",
        price: "12.000 TL",
        image: "./art/img8.jpg",
    },
    {
        id: 9,
        name: "Ali Altın",
        title: "Tuval üzerinde yağlı boya",
        size: "100 cm X 100cm",
        year: "Yapım Yılı: 2023",
        price: "45.000 TL",
        image: "./art/img9.jpg",
    },
    {
        id: 10,
        name: "Dilara Kavaklıoğlu",
        title: "Tuval üzerinde yağlı boya",
        size: "30 cm X 30cm",
        year: "Yapım Yılı: 2023",
        price: "1.500 TL",
        image: "./art/img10.jpg",
    },
]
export default CardData;